# Generated by Django 4.2.7 on 2023-12-03 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_post_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='liked_count',
            field=models.BigIntegerField(default='0'),
        ),
    ]
