# Generated by Django 4.2.7 on 2023-12-07 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_post_liked_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='liked_count',
        ),
    ]
