# Generated by Django 4.2.7 on 2023-12-07 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_post_liked_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_post',
            field=models.ImageField(blank=True, upload_to='Image_blog'),
        ),
    ]
